---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-data
  namespace: monitoring
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data-log
  namespace: monitoring
  labels:
    app: elasticsearch
    role: data
spec:
  selector:
    app: elasticsearch
    role: data
  ports:
    - name: http
      port: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data-log
  namespace: monitoring
  labels:
    app: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data-log
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: elasticsearch
      role: data
  template:
    metadata:
      annotations:
        roll_generation: "10"
      labels:
        app: elasticsearch
        role: data
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      serviceAccountName: elasticsearch
      terminationGracePeriodSeconds: 180
      containers:
        - name: elasticsearch
          #image: mintel/es-image:v7.5.1-12
          #image: mintel/elasticsearch:v7.4.1-2
          image: mintel/elasticsearch:test-test-v7.5.1-1
          #imagePullPolicy: Never
          lifecycle:
            postStart:
              exec:
                command: ["/start-data-node.sh"]
            preStop:
              exec:
                command: ["/stop-data-node.sh"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_SHARD_ALLOCATION_AWARENESS
              value: "True"
            - name: RECOVERY_MAX_BYTES
              value: 20mb
            - name: CLUSTER_NAME
              value: logs
            - name: DISCOVERY_SERVICE
              value: elasticsearch-master-log
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "true"
            - name: NODE_DATA
              value: "true"
            - name: NETWORK_HOST
              value: "0.0.0.0"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: POST_TERM_WAIT
              value: "30"
            - name: NETWORK_ADDRESS_CACHE_TTL
              value: "2"
            - name: NETWORK_ADDRESS_CACHE_NEGATIVE_TTL
              value: "2"
            # PROCESSORS NEED TO BE AN INTEGER
            - name: PROCESSORS
              value: "1"
            - name: PERSISTENT_SETTINGS_FILE_PATH
              value: "/tmp/persistent-settings.json"
            - name: MAINTENANCE_MODE
              value: "ALLOCATION"
              #value: "DELAYED_ALLOCATION"
          resources:
            requests:
              cpu: 0.15
              memory: 350Mi
            limits:
              cpu: 0.50
              memory: 1024Mi
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 30
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: storage
              mountPath: /data
            - name: persistent-settings
              mountPath: /tmp/persistent-settings.json
              subPath: settings.json
      volumes:
        - name: storage
          emptyDir: {}
        - name: persistent-settings
          configMap:
            name: persistent-settings
  #volumeClaimTemplates:
  #  - metadata:
  #      name: storage
  #    spec:
  #      accessModes:
  #      - ReadWriteOnce
  #      resources:
  #        requests:
  #          storage: 1Gi
  #      storageClassName: local-path
