apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    app: elasticsearch
  name: elasticsearch
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  labels:
    app: elasticsearch
  name: elasticsearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: monitoring

