---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: logger
  name: logger
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logger
  template:
    metadata:
      labels:
        name: logger
    spec:
      containers:
      - name: logger
        image: primeroz/random-logger:latest
        imagePullPolicy: Always
        command: [ "/entrypoint.sh" ]
        args:
        - "10"
        - "100"
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
