---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: elasticsearch-exporter
  name: elasticsearch-exporter-log
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9108
    protocol: TCP
  selector:
    name: elasticsearch-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: elasticsearch-exporter
  name: elasticsearch-exporter-log
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch-exporter
  template:
    metadata:
      labels:
        name: elasticsearch-exporter
    spec:
      containers:
      - command:
        - elasticsearch_exporter
        - --es.uri=http://elasticsearch-cluster-log:9200
        - --es.all
        - --es.cluster_settings
        - --es.indices
        - --es.indices_settings
        - --es.shards
        - --es.snapshots
        - --es.timeout=10s
        - --web.listen-address=:9108
        - --web.telemetry-path=/metrics
        image: justwatch/elasticsearch_exporter:1.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 10
        name: elasticsearch-exporter
        ports:
        - containerPort: 9108
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
          readOnlyRootFilesystem: true
      restartPolicy: Always
      securityContext:
        fsGroup: 10000
        runAsGroup: 10000
        runAsNonRoot: true
        runAsUser: 10000
