---
apiVersion: v1
kind: Service
metadata:
  name: filebeat-udp
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 9080
      targetPort: 9080
      protocol: UDP
  selector:
    name: filebeat
---
apiVersion: v1
data:
  filebeat.yml: |
    ---
    filebeat.monitoring.enabled: true
    filebeat.inputs:
      - type: tcp
        host: "0.0.0.0:9080"
        tags: [ "filebeat-test" ]
        fields:
          k8s_cluster: vault
          k8s_environment: dev
        fields_under_root: true
      - type: udp
        host: "0.0.0.0:9080"
        tags: [ "filebeat-test" ]
        fields:
          k8s_cluster: vault
          k8s_environment: dev
        fields_under_root: true
    processors:
      - decode_json_fields:
          fields: ["message"]
    setup.template:
      overwrite: true
      json:
        enabled: true
        path: "/usr/share/filebeat/filebeat.json"
        name: "filebeat"
    setup.ilm:
      enabled: true
      rollover_alias: "filebeat"
      pattern: "{now/d}-000001"
      policy_name: "filebeat"
      policy_file: "/usr/share/filebeat/filebeat_ilm_policy.json"
    output.elasticsearch:
      hosts: ["http://elasticsearch-data-log.monitoring.svc.cluster.local:9200"]
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
---
apiVersion: v1
data:
  filebeat.json: |
    {
      "order": 0,
      "version": 60001,
      "index_patterns": [
        "filebeat-*"
      ],
      "settings": {
        "index": {
          "lifecycle" : {
            "name" : "filebeat",
            "rollover_alias" : "filebeat"
          },
          "refresh_interval": "5s",
          "number_of_shards": 2,
          "number_of_replicas": 2
        }
      },
      "mappings": {
        "dynamic_templates": [
          {
            "message_field": {
              "path_match": "message",
              "match_mapping_type": "string",
              "mapping": {
                "type": "text",
                "norms": false
              }
            }
          },
          {
            "string_fields": {
              "match": "*",
              "match_mapping_type": "string",
              "mapping": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          }
        ],
        "properties": {
          "@timestamp": {
            "type": "date"
          },
          "@version": {
            "type": "keyword"
          }
        }
      }
    }
kind: ConfigMap
metadata:
  name: filebeat-template
  namespace: monitoring
---
apiVersion: v1
data:
  filebeat_ilm_policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "1h",
                "max_size": "2M"
              }
            }
          },
          "delete": {
            "min_age": "30d",
            "actions": {
              "delete": {}
            }
          },
          "warm": {
            "actions": {
              "allocate": {
                "number_of_replicas": 1
              },
              "forcemerge": {
                "max_num_segments": 1
              }
            }
          }
        }
      }
    }
kind: ConfigMap
metadata:
  name: filebeat-ilm-policy
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: filebeat
  name: filebeat
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: filebeat
    spec:
      automountServiceAccountToken: false
      containers:
      - image: docker.elastic.co/beats/filebeat-oss:7.5.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9080
          timeoutSeconds: 1
        name: flux-filebeat
        ports:
        - containerPort: 9080
          name: input-tcp
          protocol: TCP
        - containerPort: 9080
          name: input-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9080
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 150m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          mountPropagation: None
          name: filebeat-config
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/filebeat.json
          mountPropagation: None
          name: filebeat-template
          subPath: filebeat.json
        - mountPath: /usr/share/filebeat/filebeat_ilm_policy.json
          mountPropagation: None
          name: filebeat-ilm-policy
          subPath: filebeat_ilm_policy.json
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: filebeat-config
        name: filebeat-config
      - configMap:
          defaultMode: 420
          name: filebeat-template
        name: filebeat-template
      - configMap:
          defaultMode: 420
          name: filebeat-ilm-policy
        name: filebeat-ilm-policy
